name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: benchmark
      run: ./benchmark
    - name: test
      run: ./test
    - name: valgrind
      run: |
        sudo apt install -y valgrind
        valgrind -v --leak-check=full --show-leak-kinds=all ./test
